### PR TITLE
Remediated to one line

### PR DESCRIPTION
**Pull request by haggistech**
This should work better :)

### CODE REVIEW

**Comment by kz6fittycent** [comment]
just updated w/o the PR. Same stuff you added. Thanks again! Good to have other ideas than my own.

**Comment by haggistech** [comment]
why did you not merge the PR?

**Comment by kz6fittycent** [comment]
I made a couple of other changes on my local box, including yours and just copied and pasted what I had into GH. No other reason than that. Sorry didn't mean to offend.

**Comment by haggistech** [comment]
no worries dude, i just wondered lol

**Pull request closed without merging**
