### PR TITLE
checks version without downloading firs to save bandwidth

### PR DESCRIPTION
**Pull request by haggistech**
Working on a one liner but this should work in the 20 mins or so i had before work :)

### CODE REVIEW

**Comment by kz6fittycent** [comment]
```
$ curl "https://plex.tv/downloads/latest/1?channel=16&build=linux-ubuntu-x86_64&distro=ubuntu"
<html><body>You are being <a href="https://downloads.plex.tv/plex-media-server-new/1.18.2.2058-e67a4e892/debian/plexmediaserver_1.18.2.2058-e67a4e892_amd64.deb">redirected</a>.</body></html>
```

I think my first attempt was with curl and it won't work "as-is". IIRC, the reason I went with wget was that I needed to actually grab the .deb and compare it.

**Comment by haggistech** [comment]
It is here :)

https://downloads.plex.tv/plex-media-server-new/1.18.2.2058-e67a4e892/debian/plexmediaserver_
*1.18.2.2058*-e67a4e892_amd64.deb

**Comment by kz6fittycent** [comment]
```
curl "https://plex.tv/downloads/latest/1?channel=16&build=linux-ubuntu-x86_64&distro=ubuntu" | cut -d "/" -f7 | cut -d '"' -f1
```
That works...

**Comment by haggistech** [comment]
yup and this would give you just the version number

  curl "
https://plex.tv/downloads/latest/1?channel=16&build=linux-ubuntu-x86_64&distro=ubuntu"
2> /dev/null | cut -d "/" -f5  | cut -d "-" -f1


haggis@thanos:~$ curl "
https://plex.tv/downloads/latest/1?channel=16&build=linux-ubuntu-x86_64&distro=ubuntu"
2> /dev/null | cut -d "/" -f5  | cut -d "-" -f1

1.18.3.2156

**Comment by haggistech** [comment]
Remedediating

**Pull request closed without merging**
